systemd fixes , working .service file

diff --git a/scripts-dist/_upgrade b/scripts-dist/_upgrade
--- a/scripts-dist/_upgrade
+++ b/scripts-dist/_upgrade
@@ -14,6 +14,15 @@ CURRENT_VERSION=$4
 
 WWW_CONFIG=$INSTALL_DIR/www/config.php
 
+# Define the tag once
+TAG="pikrellcam"
+
+# Helper function
+log_info() {
+	logger  -t "$TAG"-i -p user.info "$1"
+}
+
+
 cd $INSTALL_DIR
 
 CURRENT_COMMIT=`git log -1 --format=%cd`
@@ -30,7 +39,21 @@ echo "inform \"$CURRENT_COMMIT\" 2 3 1" > $FIFO
 echo "inform \"Checking for upgrade...\" 3 3 1" > $FIFO
 
 git fetch  &> /dev/null
-git reset --hard origin/master 2>> $LOG_FILE
+
+log_info "Starte Git-Reset auf origin/master..."
+
+# Führe den Reset aus und fange Fehlermeldungen ab
+GIT_OUT=$(git reset --hard origin/master 2>&1)
+EXIT_CODE=$?
+
+if [ $EXIT_CODE -eq 0 ]; then
+    log_info "Git Success: $GIT_OUT"
+else
+    # Falls Git einen Fehler wirft, jede Zeile einzeln loggen
+    echo "$GIT_OUT" | while read -r line; do
+        log_info "Git ERROR (Code $EXIT_CODE): $line"
+    done
+fi
 
 NEW_VERSION=`./pikrellcam --version`
 NEW_COMMIT=`git log -1 --format=%cd`
@@ -40,11 +63,11 @@ echo "inform \" \" 3 3 1" > $FIFO
 if [ "$NEW_COMMIT" != "$CURRENT_COMMIT" ]
 then
 	echo "inform \"New commit: $NEW_COMMIT\" 4 4 1" > $FIFO
-	echo "  Upgraded to commit $NEW_COMMIT  Latest changes: $COMMIT_SUBJECT" >> $LOG_FILE
+	log_info "  Upgraded to commit $NEW_COMMIT  Latest changes: $COMMIT_SUBJECT"
 	if [ "$NEW_VERSION" != "$CURRENT_VERSION" ]
 	then
 		echo "inform \"New version: $NEW_VERSION - need restart/reload.\" 5 4 1" > $FIFO
-		echo "  Upgrade from $CURRENT_VERSION to $NEW_VERSION" >> $LOG_FILE
+		log_info "  Upgrade from $CURRENT_VERSION to $NEW_VERSION"
 
 		if ! fgrep -q $NEW_VERSION $WWW_CONFIG
 		then
@@ -53,14 +76,14 @@ then
 		fi
 	else
 		echo "inform \"Version is unchanged - recommend reload.\" 5 4 1" > $FIFO
-		echo "  Version number is unchanged." >> $LOG_FILE
+		log_info "  Version number is unchanged." >> $LOG_FILE
 	fi
 	echo "inform \"Latest changes:\" 6 4 1" > $FIFO
 	echo "inform \"$COMMIT_SUBJECT\" 7 4 1" > $FIFO
 	TIMEOUT=20
 else
 	echo "inform \"No new upgrade is available.\" 4 4 1" > $FIFO
-	echo "  No upgrade is available." >> $LOG_FILE
+	log_info "  No upgrade is available."
 	if [ "$NEW_VERSION" == "$CURRENT_VERSION" ]
 	then
 		echo "inform \"PiKrellCam is already up to date.\" 5 4 1" > $FIFO
