systemd-test1

diff --git a/scripts-dist/motion-end b/scripts-dist/motion-end
--- a/scripts-dist/motion-end
+++ b/scripts-dist/motion-end
@@ -23,6 +23,13 @@
 # you want to continue connecting so the host will be added to the list of
 # known hosts.
 #
+# Define the tag once
+TAG="pikrellcam"
+
+# Helper function
+log_info() {
+	logger  -t "$TAG"-i -p user.info "$1"
+}
 
 VIDEO_FILE=$1
 FIFO=$2
@@ -58,10 +65,27 @@ scp_video()
 	# Do the scp if the port is open.
 	if nc -zv -w 3 $host $port 2> /dev/null
 	then
-		echo "  sshpass -p $password scp -P $port $video $user@$host:$dir" >> $LOG_FILE
-		sshpass -p $password scp -P $port $video $user@$host:$dir 2>> $LOG_FILE
+		log_info "  sshpass -p $password scp -P $port $video $user@$host:$dir"
+		# 1. Den Befehl ausführen
+		# 2. Fehler in eine Variable oder direkt per Pipe umleiten
+		sshpass -p "$password" scp -P "$port" "$video" "$user@$host:$dir" 2> /tmp/scp_err
+
+		# 3. Prüfen, ob der Befehl fehlgeschlagen ist (Exit Code != 0)
+		if [ $? -ne 0 ]; then
+			while read -r line; do
+				log_info "Upload failed: $line"
+			done < /tmp/scp_err
+		else
+			log_info "Upload success: $video transfered to $host"
+		fi
+
+		# Optional: Temporäre Datei aufräumen
+		rm -f /tmp/scp_err
+
+
+
 	else
-		echo "  Cannot connect to $host:$port.  scp of $video failed." >> $LOG_FILE
+		log_info "  Cannot connect to $host:$port.  scp of $video failed."
 	fi
 	}
 
